export interface Applicant {
    appNumber: number;
    firstName: string;
    middleName: string;
    lastName: string;
    street1: string;
    street2?: string;
    city: string;
    state: string;
    zip: string;
    country: string;
    phoneNumber: string;
    phoneType: string;
    altPhoneNumber?: string;
    altPhoneType?: string;  
    email: string;
    id: number;
    lastUpdated: string;
    dateOfBirth: string;
    appType: string;
    programType: string;
    office: string;
    appDate: string;
    additionalHouseholdMembers: boolean;
    suffix?: string;
    gender: string;
    title: string;
    birthLastName: string;   
 }